name: Trigger auto deployment for ca-monitoring-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-monitoring-api-AutoDeployTrigger-fa244a5c-74c0-4d08-8e6e-b65e73cb1919.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAMONITORINGAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAMONITORINGAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAMONITORINGAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          imageToBuild: acrmonitoringapi.azurecr.io/monitoring-api:${{ github.sha }}
          containerAppName: ca-monitoring-api
          resourceGroup: rg-database-services
          registryUrl: acrmonitoringapi.azurecr.io
          acrUsername: ${{ secrets.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          targetPort: 5000
          ingress: external
          disableTelemetry: true
